root: "E:/fashion-data" # e.g. "E:/fashion-data"
raw: "00-RAW" # raw images
npy: "npy" # preprocessed .npy arrays
norm: "norm" # normalization files (.npy)
weights: "weights" # saved checkpoints
csv: "csv" # label CSV files
logs: "logs" # MLflow and other logs
mlflow_uri: "sqlite:///E:/fashion-data/logs/mlflow.db"
