max_epochs: 70
batch_size: 16
num_workers: 8
learning_rate: 1e-4
loss_function: "cross_entropy" # "cross_entropy" or "bce"
use_class_weights: true
val_split: 0.2
checkpoint_metric: "val_loss"
checkpoint_mode: "min"

augmentation:
  gamma_contrast: true
  scale: [ 0.95, 1.05 ]
  translate_px: [ -10, 10 ]
  rotate: [ -30, 30 ]
